Feature/mutations
Davi-s-Brain/Onboard-instituto pull request #14
Opened 2022-01-21 14:30 UTC by Davi-s-Brain

Adicionando mutation

2022-01-21 14:37 UTC, dan-ueno requested changes
como vc ja tem a conexão com o banco de dados, agora no resolver vc precisa puxar uma função que receba os parâmetros de input que vc definiu para  buscar ou criar dentro da entidade user que vc criou

2022-01-21 14:37 UTC, dan-ueno commented on src/database.ts
> +    url: 'postgres://postgres:postgres@localhost/postgres',
:tada:

2022-01-21 14:37 UTC, dan-ueno commented on src/index.ts
> +const { ApolloServer, gql } = require("apollo-server")
aqui vc ja pode deixar como import msm

2022-01-21 14:37 UTC, dan-ueno commented on src/index.ts
> +    createUser(nome: String, email: String, birthday: String, password: String): User!
para a mutation, vc precisa enviar todos os campos, certo? campos obrigatórios tem !

2022-01-21 14:37 UTC, dan-ueno commented on src/index.ts
> +        {_id: '1', nome:"davi", email: "davi@exemplo.com", birthday: "20-06-2541"}
seu resolver deveria se conectar com o banco, não devolver um dado mockado

2022-01-21 14:45 UTC, Davi-s-Brain commented on src/database.ts
> +    url: 'postgres://postgres:postgres@localhost/postgres',
😎

2022-01-21 14:45 UTC, Davi-s-Brain commented on src/index.ts
> +const { ApolloServer, gql } = require("apollo-server")
Feito

2022-01-21 14:47 UTC, Davi-s-Brain commented on src/index.ts
> +    createUser(nome: String, email: String, birthday: String, password: String): User!
Feito

2022-01-24 16:29 UTC, Davi-s-Brain commented on src/index.ts
> +        {_id: '1', nome:"davi", email: "davi@exemplo.com", birthday: "20-06-2541"}
Concluído

2022-01-25 15:32 UTC, dan-ueno approved these changes

2022-01-25 19:56 UTC, merged