Feature/hash
Davi-s-Brain/Onboard-instituto pull request #16
Opened 2022-01-25 14:27 UTC by Davi-s-Brain

Funcionalidade de hash na senha para adicionar no banco de dados.

2022-01-25 15:36 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +      const password = args.data.password.length < 6 || alphabet || number
aqui vc ta conferindo se a senha está dentro do padrão, então não deveria se chamar password, talvez um isValidPassword (is  pra denotar que é uma pergunta e retorna um boolean)

2022-01-25 15:37 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +      const password = args.data.password.length < 6 || alphabet || number
outro ponto que vale a pena, é que para conferencia de padrão de escrita a gente usa o Regex, dá uma olhada sobre

2022-01-25 15:38 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +      newUser.password = bcrypt.hashSync(args.data.password, 8)
se não me engano, o hash é async

2022-01-25 18:33 UTC, Davi-s-Brain commented on src/resolvers/resolvers.ts
> +      newUser.password = bcrypt.hashSync(args.data.password, 8)
Feito

2022-01-25 19:53 UTC, Davi-s-Brain commented on src/resolvers/resolvers.ts
> +      const password = args.data.password.length < 6 || alphabet || number
Feito

2022-01-26 16:39 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +        return await bcrypt.hash(text, salt).then(() => { return bcrypt.hash(text, salt) })
no caso do return não precisa dar await, ele entende que é para devolver quando tiver o dado, await vc colocaria se criasse uma const e continuasse o código

2022-01-26 16:40 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +      newUser.password = (await createHash(args.data.password)).toString()
o proprio hash já é uma string, precisa mesmo desse toString?

2022-01-26 16:41 UTC, dan-ueno requested changes
a função de hash precisa dar uma ajustada

2022-01-26 17:09 UTC, Davi-s-Brain commented on src/resolvers/resolvers.ts
> +        return await bcrypt.hash(text, salt).then(() => { return bcrypt.hash(text, salt) })
Beleza, mudei aqui

2022-01-26 17:10 UTC, Davi-s-Brain commented on src/resolvers/resolvers.ts
> +      newUser.password = (await createHash(args.data.password)).toString()
É que antes estava dando um erro dizendo que não era string, mas agora não deu

2022-01-26 17:48 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +      newUser.password = await createHash(args.data.password)
uhul!

2022-01-26 17:51 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +        return bcrypt.hash(text, salt).then(() => { return bcrypt.hash(text, salt) })
aqui acho que só dar o .hash já vai, não precisa dar .then

2022-01-26 17:55 UTC, Davi-s-Brain commented on src/resolvers/resolvers.ts
> +        return bcrypt.hash(text, salt).then(() => { return bcrypt.hash(text, salt) })
Beleza

2022-01-26 17:56 UTC, dan-ueno approved these changes

2022-01-26 18:03 UTC, merged