Feature/login
Davi-s-Brain/Onboard-instituto pull request #23
Opened 2022-02-02 14:49 UTC by Davi-s-Brain

Created the login mutation and the tests.

2022-02-02 16:06 UTC, dan-ueno commented on src/confirmation/passwordHash.ts
> +    const rounds = 7
boa, só como comentário essas informações no geral a gente deixa no env para que ngm saiba como decodificar nossas senhas olhando o código =]

2022-02-02 16:06 UTC, dan-ueno commented on test/create-user.test.ts
> +        password: await hashSupervisor.hash("ssass12A"),
mesma coisa aqui

2022-02-02 16:09 UTC, dan-ueno commented on test/login.test.ts
> +      await userRepository.save(testUser)
até essa linha é tudo arrange

2022-02-02 16:09 UTC, dan-ueno commented on test/login.test.ts
> +      const response = await createLoginMutation(data)
aqui começa o action

2022-02-02 16:09 UTC, dan-ueno commented on test/login.test.ts
> +      await userRepository.save(testUser)
vc ta salvando depois que faz a requisição?

2022-02-02 16:12 UTC, dan-ueno requested changes
tirando o arquivo de teste eu acho que  no geral está ok.
Sobre os testes:
Ainda acho estranho vc não estar utilizando o before e after each (principalmente o after, vc precisa limpar o banco a cada teste)
precisa ficar mais claro o que é arrange, action e assert....vc ta separando as linhas mas o critério não está muito claro. Dá uma pensada sobre como vc ta organizando os blocos de código e se faz sentido

2022-02-02 16:53 UTC, Davi-s-Brain commented on src/confirmation/passwordHash.ts
> +    const rounds = 7
Beleza, faz sentido mesmo

2022-02-02 16:58 UTC, Davi-s-Brain commented on test/login.test.ts
> +      await userRepository.save(testUser)
ok

2022-02-02 16:58 UTC, Davi-s-Brain commented on test/login.test.ts
> +      const response = await createLoginMutation(data)
ok

2022-02-02 17:00 UTC, Davi-s-Brain commented on test/login.test.ts
> +      await userRepository.save(testUser)
Sim

2022-02-02 17:57 UTC, Davi-s-Brain commented on test/create-user.test.ts
> +        password: await hashSupervisor.hash("ssass12A"),
Beleza

2022-02-02 18:08 UTC, dan-ueno commented on test/create-user.test.ts
> +      const hashSupervisor = new hashPassword
não seria new hasPassword() ?

2022-02-02 18:11 UTC, dan-ueno commented on test/login.test.ts
> +    it("should return ab error if the password doesn't match", async () => {
an

2022-02-02 18:13 UTC, Davi-s-Brain commented on test/create-user.test.ts
> +      const hashSupervisor = new hashPassword
verdade

2022-02-02 18:13 UTC, Davi-s-Brain commented on test/login.test.ts
> +    it("should return ab error if the password doesn't match", async () => {
Culpa do teclado

2022-02-03 00:18 UTC, dan-ueno commented on src/confirmation/clearDB.ts
> +export const clearDatabase = () => {
what?

2022-02-03 00:19 UTC, dan-ueno commented on src/confirmation/clearDB.ts
> +export const clearDatabase = () => {
man, abre o delfos api e olha um teste
https://github.com/indigotech/br-delfos-portal-api/blob/develop/src/api/graphql/module/quiz/report.test.ts

2022-02-03 00:22 UTC, dan-ueno requested changes
da uma olhada no delfos api pra ter uma boa referencia, ai vc vai entender o que eu quis dizer com limpar o banco após cada teste. no mais, com ctz o linter ta pegando agora hauahuhuaa

2022-02-03 00:46 UTC, Davi-s-Brain commented on src/confirmation/clearDB.ts
> +export const clearDatabase = () => {
Beleza, mudei hahhaha 
Eu fiz de um jeito bem estranho mesmo

2022-02-03 14:17 UTC, dan-ueno commented on src/confirmation/passwordHash.ts
> +    const rounds = process.env.ROUND;
:tada:

2022-02-03 14:20 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +    login: async (_parent: any, args: { data: { email: string; password: string } }) => {
calma, aqui nao pode ser email: string e ter um ponto e virgula, deveria ser so vigula '-'
de qqer forma, vc sempre pode criar uma interface para deixar a tipagem melhor do que colocar tudo dentro desse args

2022-02-03 14:20 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +    login: async (_parent: any, args: { data: { email: string; password: string } }) => {
nao deu pau?

2022-02-03 14:20 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +      if (!validator.email(args.data.email)) {
bem melhor 🥇

2022-02-03 14:22 UTC, dan-ueno commented on src/resolvers/resolvers.ts
> +      const response = {
aqui vc pode so colocar response = {user, token}, o graphql vai pegar os campos que precisa e devolver

2022-02-03 14:24 UTC, dan-ueno commented on test/create-user.test.ts
>      return request('localhost:4001')
aqui da pra usar a port do env, ja q ela é 4001. Se em algum momento ela trocar, ja vai estar apontada para a certa

2022-02-03 14:26 UTC, dan-ueno commented on test/create-user.test.ts
> +      const response2 = await createUserMutation(data);
a ordem de eventos ta errada

2022-02-03 14:28 UTC, dan-ueno commented on test/index.ts
> +testHello();
no geral aqui sim a gente da um require(arquivo), mas ta funfando pode deixar assim kkkkkk

2022-02-03 14:29 UTC, dan-ueno commented on test/login.test.ts
> +      await userRepository.delete(testUser);
pode tirar

2022-02-03 14:30 UTC, dan-ueno commented on test/login.test.ts
> +
pode deletar essa linha

2022-02-03 14:31 UTC, dan-ueno reviewed
para todo efeito ta aprovado, mas sempre dá para melhorar. Agora que o linter ta pegando vc viu que a forma q vc escreve o código muda os espaçamentos e tudo mais, entao vc vai acostumar a ler da mesma forma sempre....no teste ainda precisa dar uma treinada, mas ja ta mais claro

2022-02-03 14:39 UTC, Davi-s-Brain commented on src/resolvers/resolvers.ts
> +    login: async (_parent: any, args: { data: { email: string; password: string } }) => {
Tava funcionando aqui

2022-02-03 14:48 UTC, Davi-s-Brain commented on src/resolvers/resolvers.ts
> +    login: async (_parent: any, args: { data: { email: string; password: string } }) => {
Criei a interface

2022-02-03 15:02 UTC, Davi-s-Brain commented on test/index.ts
> +testHello();
kkkkkkkkkk

2022-02-03 15:03 UTC, Davi-s-Brain commented on test/login.test.ts
> +      await userRepository.delete(testUser);
Real

2022-02-03 15:04 UTC, Davi-s-Brain commented on test/login.test.ts
> +
Por que é tudo Arrange né

2022-02-03 17:48 UTC, Davi-s-Brain commented on test/create-user.test.ts
> +      const response2 = await createUserMutation(data);
agr ta certo

2022-02-03 17:51 UTC, merged